// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy_78ovcLlDPQKV_47ADCB8ZyFT8iFyW8',
    appId: '1:393694417155:web:31fd94158026b2493e1936',
    messagingSenderId: '393694417155',
    projectId: 'f1-stats-5eebe',
    authDomain: 'f1-stats-5eebe.firebaseapp.com',
    storageBucket: 'f1-stats-5eebe.appspot.com',
    measurementId: 'G-MVPQQTH1Y3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcyuYVaUg631vTexLSb3Y7ALuEkJP_yOs',
    appId: '1:393694417155:android:ba142c98fd796c463e1936',
    messagingSenderId: '393694417155',
    projectId: 'f1-stats-5eebe',
    storageBucket: 'f1-stats-5eebe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp1uiQ6yw6ohHC9-NieXPhp4e066MpDNI',
    appId: '1:393694417155:ios:a12899f7cba4fa193e1936',
    messagingSenderId: '393694417155',
    projectId: 'f1-stats-5eebe',
    storageBucket: 'f1-stats-5eebe.appspot.com',
    iosClientId: '393694417155-r5nh7t17tcd5m5m51uns7sgejom5n2mv.apps.googleusercontent.com',
    iosBundleId: 'com.example.f1Stats',
  );
}
